filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
releases:
- chart: dev/jkx-golang2
  version: 0.0.2
  name: jkx-golang2
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
