apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        borderx/jks-boot1: true
        borderx/jx-test3: true
        borderx/jx3-minikube: true
        borderx/jx4: true
        borderx/jx5: true
        borderx/jx7: true
        borderx/spoot: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        borderx/jks-boot1: merge
        borderx/jx-test3: merge
        borderx/jx3-minikube: merge
        borderx/jx4: merge
        borderx/jx5: merge
        borderx/jx7: merge
        borderx/spoot: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - borderx/jx3-minikube
        - borderx/jks-boot1
        - borderx/jx-test3
        - borderx/jx4
        - borderx/jx5
        - borderx/jx7
        - borderx/spoot
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - borderx/jx3-minikube
        - borderx/jks-boot1
        - borderx/jx-test3
        - borderx/jx4
        - borderx/jx5
        - borderx/jx7
        - borderx/spoot
      target_url: http://lighthouse-jx.192.168.64.3.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
